# 绑定地址
bind_address: "0.0.0.0"

# 端口
port: 17128

# 节点地址
url: "wss://eu.openledger.info/ws"

# 帐号名称
account: "YOUACCOUNT"

# 帐号私钥
wifkey: "YOUBITSHARESWIF"

# 应用服务地址
casino_address: "172.17.0.1"

# 应用服务端口
casino_port: 12180

# 记录器配置
mysql_logger:
  host: "172.17.0.1"
  port: 3306
  user: "root"
  passwd: ""
  database: "casino_logs"
